SELECT 
    c1.CAR_ID, 
    c1.CAR_TYPE, 
    ROUND(c1.DAILY_FEE * 30 * (100 - c2.DISCOUNT_RATE) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR c1
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN c2 
    ON c1.CAR_TYPE = c2.CAR_TYPE AND c2.DURATION_TYPE = '30일 이상'
WHERE 
    c1.CAR_TYPE IN ('세단', 'SUV')
    AND c1.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
    )
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    c1.CAR_TYPE ASC, 
    c1.CAR_ID DESC;