SELECT f1.PRODUCT_ID, f1.PRODUCT_NAME, f1.PRICE * SUM(f2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT f1
JOIN FOOD_ORDER f2 ON f1.PRODUCT_ID = f2.PRODUCT_ID
WHERE YEAR(f2.PRODUCE_DATE) = 2022 AND MONTH(f2.PRODUCE_DATE) = 5
GROUP BY f1.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, f1.PRODUCT_ID ASC