SELECT 
    h.HISTORY_ID,
    FLOOR(
        (DATEDIFF(h.END_DATE, h.START_DATE) + 1)
        * c.DAILY_FEE
        * (1 - (
            CASE 
                WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN IFNULL(p90.DISCOUNT_RATE, 0) / 100
                WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN IFNULL(p30.DISCOUNT_RATE, 0) / 100
                WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN IFNULL(p7.DISCOUNT_RATE, 0) / 100
                ELSE 0
            END
        ))
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN 
    CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p7 
    ON c.CAR_TYPE = p7.CAR_TYPE AND p7.DURATION_TYPE = '7일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p30 
    ON c.CAR_TYPE = p30.CAR_TYPE AND p30.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p90 
    ON c.CAR_TYPE = p90.CAR_TYPE AND p90.DURATION_TYPE = '90일 이상'
WHERE 
    c.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, h.HISTORY_ID DESC;