SELECT RANKING.FLAVOR
FROM (SELECT f.FLAVOR, SUM(f.TOTAL_ORDER) AS TOTAL
     FROM FIRST_HALF f
     GROUP BY f.FLAVOR
     UNION
     SELECT j.FLAVOR, SUM(j.TOTAL_ORDER) AS TOTAL
     FROM JULY j
     GROUP BY j.FLAVOR
     ) AS RANKING
GROUP BY RANKING.FLAVOR
ORDER BY SUM(RANKING.TOTAL) DESC
LIMIT 3