WITH sum_front AS (SELECT sum(CODE) AS total
FROM SKILLCODES
WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT total FROM sum_front) > 0
ORDER BY ID