WITH TOP AS (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1)
                   
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = (SELECT * FROM TOP)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC

# SELECT *
# FROM MEMBER_PROFILE
# WHERE MEMBER_ID IN (SELECT MEMBER_ID
#                    FROM REST_REVIEW
#                    GROUP BY MEMBER_ID
#                    ORDER BY COUNT(*) DESC)