SELECT c1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY c2 ON c1.CAR_ID = c2.CAR_ID
WHERE c1.CAR_TYPE = '세단'
AND MONTH(c2.START_DATE) = 10
GROUP BY c1.CAR_ID
ORDER BY c1.CAR_ID DESC