SELECT CONCAT('/home/grep/src/', u2.BOARD_ID, '/' , u2.FILE_ID , u2.FILE_NAME, u2.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD u1
JOIN USED_GOODS_FILE u2 ON u1.BOARD_ID = u2.BOARD_ID
WHERE u1.BOARD_ID = (SELECT BOARD_ID
                    FROM USED_GOODS_BOARD
                    ORDER BY VIEWS DESC
                    LIMIT 1)
ORDER BY u2.FILE_ID DESC