WITH CODE_TABLE AS (
    SELECT 
        MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON,
        MAX(CASE WHEN NAME = 'C#' THEN CODE END) AS C_SHARP,
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END
    FROM SKILLCODES
)

SELECT 
    CASE 
        WHEN (d.SKILL_CODE & c.FRONT_END) > 0 AND (d.SKILL_CODE & c.PYTHON) > 0 THEN 'A'
        WHEN (d.SKILL_CODE & c.C_SHARP) > 0 THEN 'B'
        WHEN (d.SKILL_CODE & c.FRONT_END) > 0 THEN 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d
JOIN CODE_TABLE c
HAVING GRADE IS NOT NULL
ORDER BY GRADE, d.ID;